import icon1 from "../../../../../assets/icons/afterLogin/functions/camera-green.svg"
import icon2 from "../../../../../assets/icons/afterLogin/functions/Scorecard.svg"
import icon3 from "../../../../../assets/icons/afterLogin/functions/Lightning-Bolt.svg"
import FunctionCard from "../../common/functionsCard/FunctionsCard"
import './FunctionsSection.css'

function FunctionsSection() {

    const ReceiverFunctionData = [
        {
            id: 1,
            icon: icon1,
            title: "Real-Time Listing Discovery",
            description: "Instantly view Live Drops from nearby restaurants and supermarkets via the high-performance location-based map."
        },
        {
            id: 2,
            icon: icon2,
            title: "Zero-Lag Claiming System",
            description: "Eliminate manual coordination bottlenecks by claiming available surplus food pins before they expire."
        },
        {
            id: 3,
            icon: icon3,
            title: "Automated Categorization",
            description: "Receive detailed data on food types (e.g., Bakery, Cooked Grains) and estimated portions generated by AI vision models."
        },
    ];


    return (

        <div className="function__section">
            <h1>Navigate & Claim</h1>
            <p>Advanced tools for the modern surplus hero</p>
            <div className="function__section__s1">
                {ReceiverFunctionData.map((stat) => (
                    <FunctionCard
                        key={stat.id}
                        icon={stat.icon}
                        title={stat.title}
                        description={stat.description}
                    />
                ))}
            </div>
        </div>
    )
}

export default FunctionsSection;